services:
  web:
    build: .
    environment:
      - KTOR_CONFIG=/app/application.conf
    ports:
      - "80:8080"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: tennis
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: password_a
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s

volumes:
  db_data: