services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - sqlite_data:/data/database.db
    environment:
      - KTOR_CONFIG=/app/application.conf
    ports:
      - "80:8080"

volumes: 
  sqlite_data: