services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data # Mount the database directory
    ports:
      - "80:8080"  # Map port 8080 of the container to port 8080 on the host
    environment:
      - DATABASE_URL=jdbc:sqlite:/app/data/database.db  # Set the database URL